name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Main build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: "temurin"
          cache: gradle

      - name: Build release
        run: ./gradlew assembleRelease --profile

      - name: Upload release APK and build profile artifact
        uses: actions/upload-artifact@v6
        with:
          name: android-release-and-build_profile
          path: |
            app/build/outputs/apk/release/*.apk
            build/reports/profile/profile-*.html

  gradle_lint:
    name: "Gradle lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: "temurin"
          cache: gradle

      - name: Lint
        run: ./gradlew lint

      - name: Upload lint reports
        uses: actions/upload-artifact@v6
        with:
          name: lint-reports-html
          path: app/build/reports/lint-results-*.html

  gradle_test:
    name: "Gradle unittest"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: "temurin"
          cache: gradle

      - name: Unit test
        run: ./gradlew testReleaseUnitTest

  lint_ktlint:
    name: Ktlint lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_KOTLIN: true
          DISABLE_ERRORS: false

  cargo-build:
    name: "Rust cargo build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Install stable rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          workspaces: |
            import_export_helper/

      - name: Cargo build
        run: |
          cd ./import_export_helper/
          cargo build --release --bin watchAppHelper
          echo "tui mode"
          cargo build --release --bin watchAppHelper-Tui

      - name: Upload helper bin
        uses: actions/upload-artifact@v6
        with:
          name: rust_helper_bins_cli_tui
          path: |
            import_export_helper/target/release/watchAppHelper
            import_export_helper/target/release/watchAppHelper-Tui

  cargo-clippy:
    name: "Rust cargo clippy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Install stable rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          workspaces: |
            import_export_helper/

      - name: Rust clippy
        run: |
          cd ./import_export_helper/
          cargo clippy --all --all-targets

  cargo-fmt:
    name: "Rust cargo fmt"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Install rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Rust fmt
        run: |
          cd ./import_export_helper/
          cargo +nightly fmt --check --all

  androidTest:
    runs-on: ubuntu-latest
    name: "androidTest API ${{ matrix.api-level }}"
    timeout-minutes: 55
    strategy:
      fail-fast: false
      matrix:
        api-level: [33]

    steps:
      - uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: "temurin"
          cache: gradle

      - name: Show machine stats
        run: |
          lscpu || echo ""
          lsmem || echo ""

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: android-wear
          arch: x86_64
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Build and run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: android-wear
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          arch: x86_64
          disable-animations: true
          disk-size: 6000M
          heap-size: 600M
          ram-size: 2048M
          cores: 2
          script: |
            adb logcat -c
            touch app/emulator.log
            adb logcat > app/emulator.log &
            ./gradlew connectedAndroidTest --daemon

      - name: Upload test reports
        uses: actions/upload-artifact@v6
        with:
          name: instrumentation-test-reports-html
          path: |
            app/build/reports/androidTests/connected/debug/*.html
            app/build/reports/androidTests/connected/release/*.html
            app/emulator.log
