name: Draft Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  draft-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: "temurin"
          cache: gradle

      - name: Install stable rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          workspaces: |
            import_export_helper/

      - name: Build release APK
        run: |
          ./gradlew assembleRelease

      - name: Signing APK
        id: sign_app
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.SIGN_KEY_BASE64 }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWD }}
          keyPassword: ${{ secrets.KEY_PASSWD }}
          buildToolsVersion: 35.0.0

      - name: Cargo build
        run: |
          cd ./import_export_helper/
          cargo build --release --bin watchAppHelper
          echo "tui mode"
          cargo build --release --bin watchAppHelper-Tui

      - name: prepare .tar.xz containing all binaries and app
        run: |
          mkdir app-out
          mv ${{ steps.sign_app.outputs.signedFile }} ./app-out/app-v${{ github.event.inputs.version }}-release-signed.apk
          mv import_export_helper/target/release/watchAppHelper ./app-out/watchAppHelper-v${{ github.event.inputs.version }}
          mv import_export_helper/target/release/watchAppHelper-Tui ./app-out/watchAppHelper-Tui-v${{ github.event.inputs.version }}

      - name: Create app tar
        run: |
          tar jcvf app-v${{ github.event.inputs.version }}.tar.xz app-out/*

      - name: Draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: v${{ github.event.inputs.version }}
          files: |
            app-v${{ github.event.inputs.version }}.tar.xz
            ./app-out/app-v${{ github.event.inputs.version }}-release-signed.apk
            ./app-out/watchAppHelper-v${{ github.event.inputs.version }}
            ./app-out/watchAppHelper-Tui-v${{ github.event.inputs.version }}
          fail_on_unmatched_files: true
